### ISSUE TITLE
Address Sanitizer is only intended for debugging

### ISSUE THREAD

**Issue by fdopen** [fxfactorial/ocaml-brotli#2]
The 'address sanitizer' is only intended for debugging. Don't add it to production code: https://github.com/fxfactorial/ocaml-brotli/blob/3b564c2182ca04b444ea2e2a815ea0ed5c9c711c/_oasis#L33

See: http://seclists.org/oss-sec/2016/q1/363

**Comment by fxfactorial** [comment]
ahhh, I forgot and left that in, aware of the production issues. Will fix now.

**Comment by fxfactorial** [comment]
Fixed and force pushed for the opam repo PR
