### ISSUE TITLE
Is C++14 necessary?

### ISSUE THREAD

**Issue by mroch** [fxfactorial/ocaml-brotli#3]
I'm trying to install on CentOS 7, which has gcc 4.8.5, which doesn't support c++14. brotli itself has a travis config that builds with gcc-4.4 so it must not depend on c++14. is the `-std=c++14` flag in _oasis for the stubs? if so, can the newfangled stuff be downgraded for better compatibility?

```
### stdout ###
# ocamlfind ocamlopt unix.cmxa -I /home/mroch/.opam/4.05.0+spacetime/lib/ocamlbuild /home/mroch/.opam/4.05.0+spacetime/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /home/mroch/.opam/4.05.0+spacetime/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /home/mroch/.opam/4.05.0+spacetime/bin/ocamlfind ocamlc -g -ccopt -Wextra -ccopt -fno-omit-frame-pointer -ccopt -fsanitize-undefined-trap-on-error -ccopt -O2 -ccopt -fno-optimize-sibling-calls -ccopt '-std=c++14' -ccopt -x -ccopt c++ -ccopt -I/usr/local/include -package unix -c src/brotli_stubs.c
# + /home/mroch/.opam/4.05.0+spacetime/bin/ocamlfind ocamlc -g -ccopt -Wextra -ccopt -fno-omit-frame-pointer -ccopt -fsanitize-undefined-trap-on-error -ccopt -O2 -ccopt -fno-optimize-sibling-calls -ccopt '-std=c++14' -ccopt -x -ccopt c++ -ccopt -I/usr/local/include -package unix -c src/brotli_stubs.c
# gcc: error: unrecognized command line option ‘-fsanitize-undefined-trap-on-error’
# gcc: error: unrecognized command line option ‘-std=c++14’
# Command exited with code 2.
```

```
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
```

**Comment by fxfactorial** [comment]
Sure, will downgrade. I think latest brotli broke stubs anyway so I needed to return to it anyway

**Comment by fxfactorial** [comment]
@mroch Okay, so I downgraded the requirement to `C++11` and updated the bindings to work with latest brotli, should be good once this is accepted: https://github.com/ocaml/opam-repository/pull/10431 on opam or you can just locally pin it.

**Comment by fxfactorial** [comment]
Oh wait, I think `‘-fsanitize-undefined-trap-on-error’` might still crap out as well.

**Comment by fxfactorial** [comment]
@mroch that one was removed as well now from the build, so a gcc on centos i think ought to build fine.

**Comment by mroch** [comment]
```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed brotli.2.0.1
Done.
```

it works, thank you! 🥇
